title: 2019-1-OSS-L1 # your site title
author: OSS-L1
email: joeyadamcho@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/2019-1-OSS-L1" # the subpath of your site, e.g. /blog
url: "https://19-1-skku-oss.github.io/2019-1-OSS-L1" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cjy12182000  # replace with your_twitter_username or comment to remove link from footer
github_username:  joeycho # replace with your_github_username or comment to remove link from footer
instagram_username: cho.joey # replace with your_instagram_username or comment to remove link from footer
social:
  name: Team L1
  links:
    - https://twitter.com/cjy12182000
    - https://www.facebook.com/
    - https://www.linkedin.com/in/
    - https://plus.google.com/
    - https://github.com/joeycho
    - https://keybase.io/

disqus:
  shortname: oss_L1 # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek
exclude:
  - README.md
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.png

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
 
g-analytics: G-GH7JQE29L0
